// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy8JGbpUQeXJ6RgBcfLOKCBG9MlCb0Akw',
    appId: '1:978829565704:web:c45a20cccc377b46cc16bd',
    messagingSenderId: '978829565704',
    projectId: 'clinick-api',
    authDomain: 'clinick-api.firebaseapp.com',
    storageBucket: 'clinick-api.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB69ZZixq-Ty14bRObnFGcNBeuiY-1jR9M',
    appId: '1:978829565704:android:2d960fb7ace17e5ccc16bd',
    messagingSenderId: '978829565704',
    projectId: 'clinick-api',
    storageBucket: 'clinick-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRc5xEHoE2URL-mBSMSYzZdpsxtb8bfX4',
    appId: '1:978829565704:ios:2e35c40512582134cc16bd',
    messagingSenderId: '978829565704',
    projectId: 'clinick-api',
    storageBucket: 'clinick-api.appspot.com',
    iosClientId: '978829565704-g2nf3sshbsm93hajds8hrlala3njmcbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.clinickClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRc5xEHoE2URL-mBSMSYzZdpsxtb8bfX4',
    appId: '1:978829565704:ios:2e35c40512582134cc16bd',
    messagingSenderId: '978829565704',
    projectId: 'clinick-api',
    storageBucket: 'clinick-api.appspot.com',
    iosClientId: '978829565704-g2nf3sshbsm93hajds8hrlala3njmcbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.clinickClient',
  );
}
